name: 'Get and Cache Dependencies'
description: 'Get dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'true - to use caching, false - to suppress caching and always install dependencies'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.install.outputs.cache || 'true' }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: inputs.caching != 'true' || steps.cache.outputs.cache-hit != 'true'
      #echo "cache='false'" >> $GITHUB_OUTPUT
      run: |
        npm ci         
        echo "::set-output name=cache::'false'"
      shell: bash